name: CI Tests

on: [workflow_dispatch]

jobs:
  e2e-android-debug:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn

      # Lock Java version to JDK 8 which is used by React Native
      - name: Use specific Java version for the builds
        uses: joschi/setup-jdk@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          java-version: 'openjdk8'
          architecture: 'x64'

      # Make a build of the Android app
      - name: Build Android app
        run: |
          npx detox build -c android.emu.debug.ci

      # Install an Android emulator with SDK 30 (Android 11) with the name: Nexus_6P
      - name: Download Android emulator
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-30;google_apis;x86"
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name Nexus_6P --device "Nexus 6P" -k 'system-images;android-30;google_apis;x86'
          $ANDROID_HOME/emulator/emulator -list-avds

      # Boot our Android emulator
      - name: Boot Android emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd Nexus_6P -no-audio -no-snapshot -no-window &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          $ANDROID_HOME/platform-tools/adb devices

      # Boot metro and run tests
      # Metro is required because Detox uses debug builds of the app
      - name: boot metro server, install build and run tests
        run: |
          adb reverse tcp:8081 tcp:8081
          (yarn start&)
          PID=$(ps $! | tail -1 | awk '{print $1}')
          npx detox test -c android.emu.debug.ci --headless
          echo $PID
          # kill $PID

      - name: Save Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            artifacts
